/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        System.out.println("this test case should not run");
        assertTrue("someLibraryMethod should return 'false'", classUnderTest.someLibraryMethod());
    }
}
